name: NodeJS-Graph CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: ['14.17.0']
    steps:
      - uses: actions/checkout@v2.3.4
      - run: npm ci
  publish-npm:
    needs: build
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: ['14.17.0']
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
